zookeeper:
  image: jplock/zookeeper
  ports:
    - 2181:2181
mesos-master:
  image: mesosphere/mesos-master:0.27.1-2.0.226.ubuntu1404
  ports:
    - 5050:5050
  command: --zk=zk://192.168.99.100:2181/mesos --registry=in_memory --advertise_ip=192.168.99.100  --no-hostname_lookup
  links:
    - zookeeper
mesos-slave:
  image: mesosphere/mesos-slave:0.27.1-2.0.226.ubuntu1404
  net:  "host"
  command: --master=192.168.99.100:5050  --containerizers=docker,mesos --docker=/usr/local/bin/docker --advertise_ip=192.168.99.100 --no-hostname_lookup
  privileged: true
  volumes:
    - /usr/local/bin/docker:/usr/local/bin/docker
    - /var/run/docker.sock:/var/run/docker.sock
marathon:
  image: mesosphere/marathon
  ports:
    - 8080:8080
  command: --master zk://192.168.99.100:2181/mesos --zk zk://192.168.99.100:2181/marathon --hostname 192.168.99.100 --event_subscriber http_callback --artifact_store file:///tmp/

logger:
  image: fluent/fluentd
  ports:
    - 514:5140/udp
    - 24224:24224
  volumes:
    - ./fluent.conf:/fluentd/etc/fluent.conf

haproxy:
  image: kodokojo/kodokojo-haproxy-marathon
  ports:
    - 80:80
    - 443:443
    - 4444:4444
  environment:
    - PORT=4444
    - MARATHON_URL=http://192.168.99.100:8080
    - MARATHON_URL_CALLBACK=http://192.168.99.100:4444/callback
